# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.6

env:
  - TOXENV=py36
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py27

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: masasin
  password:
    secure: PLEASE REPLACE ME
  on:
    tags: true
    repo: masasin/pyrosbag
    condition: $TOXENV == py27
